### ISSUE TITLE
Specify margin

### ISSUE THREAD

**Issue by LenonBordini** [jsreport/jsreport-html-embedded-in-docx#1]
Hi, is there a way to specify the **margin** of the docx?

I couldn't find anywhere.

Here's my code:

```node
const jsreport = require('jsreport-core')({
    tasks: { strategy: 'in-process' }
});

jsreport.use(require('jsreport-html-embedded-in-docx')());

await jsreport.init();
let docx = await jsreport.render({
    template: {
        content: '<html>...</html>',
        engine: 'none',
        recipe: 'html-embedded-in-docx'
    }
});

```

**Comment by pofider** [comment]
This should work

```html
<html>
    <head>
        <style>
            body, html {
                margin: 100px
            }
        </style>
    </head>
    <body>
        foo
    </body>
</html>
```

**Comment by LenonBordini** [comment]
Thank you for quick answer.

I wanted to decrease the size of this space:

<a href="https://ibb.co/q9p9wwT"><img src="https://i.ibb.co/wC4C115/msword.png" alt="msword" border="0"></a>

With negative margin worked, but only left and right, top didn't changed, but is already better, thank you again.

```css
body, html {
    margin: -40px;
}
```
